module.exports = {
  100: 'Continue',
  101: 'Switching protocols',
  102: 'Processing',
  200: 'Ok',
  201: 'Created',
  202: 'Accepted',
  203: 'Non-authoritative information',
  204: 'No content',
  205: 'Reset content',
  206: 'Partial content',
  207: 'Multi-status',
  300: 'Multiple choices',
  301: 'Moved permanently',
  302: 'Moved temporarily',
  303: 'See other',
  304: 'Not modified',
  305: 'Use proxy',
  307: 'Temporary redirect',
  400: 'Bad request',
  401: 'Unauthorized',
  402: 'Payment required',
  403: 'Forbidden',
  404: 'Not found',
  405: 'Method not allowed',
  406: 'Not acceptable',
  407: 'Proxy authentication required',
  408: 'Request time-out',
  409: 'Conflict',
  410: 'Gone',
  411: 'Length required',
  412: 'Precondition failed',
  413: 'Request entity too large',
  414: 'Request-uri too large',
  415: 'Unsupported media type',
  416: 'Requested range not satisfiable',
  417: 'Expectation failed',
  418: "I'm a teapot",
  422: 'Unprocessable entity',
  423: 'Locked',
  424: 'Failed dependency',
  425: 'Unordered collection',
  426: 'Upgrade required',
  428: 'Precondition required',
  429: 'Too many requests',
  431: 'Request header fields too large',
  500: 'Internal server error',
  501: 'Not implemented',
  502: 'Bad gateway',
  503: 'Service unavailable',
  504: 'Gateway time-out',
  505: 'Http version not supported',
  506: 'Variant also negotiates',
  507: 'Insufficient storage',
  509: 'Bandwidth limit exceeded',
  510: 'Not extended',
  511: 'Network authentication required',
  RESOURCE_FORBIDDEN: {
    status: 403,
    message: 'Forbidden Error',
    code: 'RESOURCE_FORBIDDEN'
  },
  UNAUTHORIZED: {
    status: 403,
    message: 'UNAUTHORIZED Error',
    code: 'UNAUTHORIZED'
  }
};
